#Set the range of Chocolate Fountain (in Blocks)
#Range: > 0
chocolate_fountain_range = 10
#Set the internal Tank Capacity of the Chocolate Fountain (in mB)
#Range: > 0
chocolateFountainTankCapacity = 1000
#Amount of Chocolate consumed when autofeeding the Player (in mB)
#Range: > 0
chocolateFountainConsumedPerUsage = 250
#Time between possible feeding actions (in ticks)
#Range: > 1
chocolateFountainCooldown = 40
#Amount of Food added to the Player)
#Range: 0 ~ 20
chocolateFountainFoodAmount = 3
#Amount of Saturation added to the Player
#Range: 0.0 ~ 20.0
chocolateFountainSaturationAmount = 0.3

